name: Daily House Scraper

on:
  schedule:
    - cron: '0 14 * * *'  # Runs daily at 8:00 AM CST (UTC-6)
  workflow_dispatch:  # Allows manual runs from GitHub UI

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Run Zillow56 scraper
      env:
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
        GITHUB_ACTIONS: true
      run: |
        python zillow56_scraper.py
    
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: house-listings-${{ github.run_number }}
        path: house_listings_*.csv
        retention-days: 30


